name: Lint, test and package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev

    - name: Run minimal linting
      run: pipenv run lint-minimal

    - name: Run mypy scan
      run: pipenv run mypy

    - name: Run test cases
      run: pipenv run test

    - name: Package
      run: |
        pipenv run package
        pipenv run package-onefile

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ffsds4-amd64
        path: dist/*
